### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by KrisDevelopment** [ytisf/BirDuster#1]
After running .local/bin/BirDuster.py somedomain.com -o birdust.txt
outputs error:
```

Traceback (most recent call last):
  File "/home/kr1s/.local/bin/BirDuster.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Kali linux on WSL 2
Python 3.10.4

**Comment by its0din-ai** [comment]
for Users => You can Install using `pip3 install requests`. Make sure, pip is installed, check it using `pip3 --version`

for Dev => add requests to requirements.txt

**Comment by KrisDevelopment** [comment]
That fixes it. Thanks.
